# --- Base Stage ---
FROM node:18-slim AS base
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm

# --- Dependencies Stage ---
FROM base AS deps
COPY package.json pnpm-lock.yaml* ./
# Gunakan cache terpisah untuk instalasi dependensi
RUN --mount=type=cache,target=/root/.pnpm-store \
    pnpm install --frozen-lockfile --prod=false --ignore-scripts

# --- Development Stage ---
# Stage ini hanya digunakan untuk pengembangan lokal, tidak akan menjadi image produksi
FROM base AS development
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
RUN pnpm run build:icons
EXPOSE 3010
CMD ["pnpm", "run", "dev"]

# --- Builder Stage ---
FROM base AS builder
COPY --from=deps /app/node_modules /app/node_modules
COPY . .
# Gunakan cache untuk build Nuxt/Vite
RUN --mount=type=cache,target=/app/.nuxt \
    --mount=type=cache,target=/app/node_modules/.vite \
    pnpm run build:icons && \
    pnpm run build

# --- Runtime Stage ---
# Tahap final untuk menjalankan aplikasi produksi
FROM node:18-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production # Ini memastikan Nuxt berjalan dalam mode produksi
COPY --from=builder /app/.output ./.output # Salin output build Nuxt
COPY --from=builder /app/public ./public # Salin aset publik
EXPOSE 3010 # Ekspos port aplikasi
CMD ["node", ".output/server/index.mjs"] # Perintah untuk menjalankan aplikasi Nuxt produksi