"""
Environment configuration fix script for hotspot-portal

This script creates or updates .env.override files to fix common
configuration issues, particularly focusing on login loop problems
caused by explicit device authorization requirements.

Usage:
docker-compose exec backend python scripts/fix_env_config.py [--revert]
"""

import os
import sys
import shutil
from datetime import datetime

# Color codes for terminal
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
RESET = "\033[0m"

# Configuration settings that will be applied
ENV_FIXES = {
    # Disable device authorization requirement to fix login loop
    "REQUIRE_EXPLICIT_DEVICE_AUTH": "False",
    
    # Ensure sessions are using Redis
    "SESSION_TYPE": "redis",
    
    # Set explicit Redis URL if needed
    # "REDIS_URL": "redis://redis:6379/1",
}

def backup_file(filepath):
    """Create a backup of a file if it exists"""
    if os.path.exists(filepath):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = f"{filepath}.bak_{timestamp}"
        try:
            shutil.copy2(filepath, backup_path)
            print(f"{GREEN}[BACKUP]{RESET} Created backup at {backup_path}")
            return backup_path
        except Exception as e:
            print(f"{RED}[ERROR]{RESET} Failed to create backup: {e}")
    return None

def update_env_override(revert=False):
    """Create or update .env.override file with fixes"""
    env_path = ".env"
    override_path = ".env.override"
    
    # First, make a backup of any existing .env.override
    backup_file(override_path)
    
    if revert:
        if os.path.exists(override_path):
            try:
                os.remove(override_path)
                print(f"{GREEN}[REVERTED]{RESET} Removed .env.override file")
            except Exception as e:
                print(f"{RED}[ERROR]{RESET} Failed to remove .env.override: {e}")
        return
    
    # Read existing .env file to understand the environment
    env_vars = {}
    if os.path.exists(env_path):
        try:
            with open(env_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        env_vars[key.strip()] = value.strip()
        except Exception as e:
            print(f"{YELLOW}[WARNING]{RESET} Failed to read .env file: {e}")
    
    # Read existing .env.override if it exists
    override_vars = {}
    if os.path.exists(override_path):
        try:
            with open(override_path, 'r') as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith('#') and '=' in line:
                        key, value = line.split('=', 1)
                        override_vars[key.strip()] = value.strip()
        except Exception as e:
            print(f"{YELLOW}[WARNING]{RESET} Failed to read .env.override file: {e}")
    
    # Merge fixes with existing overrides
    updated_vars = override_vars.copy()
    updated_vars.update(ENV_FIXES)
    
    # Write updated .env.override file
    try:
        with open(override_path, 'w') as f:
            f.write("# Generated by fix_env_config.py on {}\n".format(
                datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            ))
            f.write("# This file overrides settings in .env to fix login loop issues\n\n")
            
            for key, value in updated_vars.items():
                f.write(f"{key}={value}\n")
        
        print(f"{GREEN}[SUCCESS]{RESET} Created/updated .env.override file with fixes")
        print(f"{BLUE}[INFO]{RESET} The following settings were applied:")
        
        for key in ENV_FIXES:
            status = GREEN if key in updated_vars else YELLOW
            value = updated_vars.get(key, "Not set")
            print(f"  {status}{key}={value}{RESET}")
            
        print(f"\n{YELLOW}[IMPORTANT]{RESET} You need to restart the backend container for changes to take effect:")
        print(f"{BLUE}docker-compose restart backend{RESET}")
        
    except Exception as e:
        print(f"{RED}[ERROR]{RESET} Failed to write .env.override file: {e}")

def show_help():
    """Show help information"""
    print(f"\n{YELLOW}[ENVIRONMENT FIX TOOL HELP]{RESET}")
    print(f"Usage: python scripts/fix_env_config.py [--revert]")
    print(f"  --revert: Remove the .env.override file to restore original settings")
    print(f"  --help: Show this help message")
    print(f"\nThis script creates an .env.override file that disables explicit device authorization")
    print(f"to fix login loop issues. It preserves existing override settings.")

def main():
    """Main function"""
    print(f"{YELLOW}{'='*50}{RESET}")
    print(f"{YELLOW}[ENVIRONMENT CONFIGURATION FIX TOOL]{RESET}")
    print(f"{YELLOW}{'='*50}{RESET}")
    
    if "--help" in sys.argv or "-h" in sys.argv:
        show_help()
        return
    
    revert_mode = "--revert" in sys.argv
    
    if revert_mode:
        print(f"{YELLOW}[REVERT MODE]{RESET} Removing environment overrides...")
    else:
        print(f"{YELLOW}[FIX MODE]{RESET} Applying environment fixes...")
    
    update_env_override(revert=revert_mode)

if __name__ == "__main__":
    main()
