# mikrotik_client.pyi - Type stub for mikrotik_client module
from typing import Optional, Any, Tuple, Dict

def disable_ip_binding_by_comment(comment: str) -> Tuple[bool, str]: ...
def delete_ip_binding_by_comment(comment: str) -> Tuple[bool, str]: ...
def create_or_update_ip_binding(mac_address: str, ip_address: str, comment: str, server: Optional[str] = None, type: str = 'bypassed') -> Tuple[bool, str]: ...
def find_mac_by_ip_comprehensive(ip_address: str, force_refresh: bool = False) -> Tuple[bool, Optional[str], str]: ...
def get_active_session_by_ip(ip_address: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def find_and_update_address_list_entry(list_name: str, address: str, new_comment: Optional[str] = None) -> Tuple[bool, str]: ...
def find_and_remove_static_lease_by_mac(mac: str) -> Tuple[bool, str]: ...
def create_static_lease(ip: str, mac: str, comment: str) -> Tuple[bool, str]: ...
def purge_user_from_hotspot(username: str) -> Tuple[bool, str]: ...
def purge_user_from_hotspot_by_comment(comment: str) -> Tuple[bool, str]: ...
def get_hotspot_user_details(username: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def set_hotspot_user_profile(username: str, new_profile_name: str) -> Tuple[bool, str]: ...
def get_ip_binding_details(username_comment: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def get_host_details_by_mac(mac_address: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def get_host_details_by_username(username: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def reset_host_counters(host_id: str) -> Tuple[bool, str]: ...
def get_host_details_by_ip(ip_address: str) -> Tuple[bool, Optional[Dict[str, Any]], str]: ...
def get_mac_from_dhcp_lease(ip_address: str) -> Tuple[bool, Optional[str], str]: ...
def ensure_ip_binding_status_matches_profile(username: str, target_profile: str) -> Tuple[bool, str]: ...
def add_ip_to_address_list(list_name: str, ip: str, comment: str) -> Tuple[bool, str]: ...
def remove_ip_from_address_list(list_name: str, ip: str) -> Tuple[bool, str]: ...
def remove_ip_from_all_address_lists(ip: str) -> Tuple[bool, str]: ...
def move_user_to_inactive_list(user_ip: str, comment: str) -> Tuple[bool, str]: ...
def get_mikrotik_connection(): ...
def delete_hotspot_user(api: Any, username: str) -> Tuple[bool, str]: ...
def format_to_local_phone(phone: str) -> Optional[str]: ...
def purge_client_traces(ip_address: str, mac_address: Optional[str] = None, include_binding: bool = False) -> Dict[str, Tuple[bool, str]]: ...
