"""
Test script to check Redis connection, environment variables, and fix issues.
Run this inside the backend container to diagnose and repair environment issues.
"""
import os
import sys
import redis
from datetime import datetime
import time

def print_header(text):
    """Print a formatted header"""
    print("\n" + "=" * 80)
    print(f" {text} ".center(78, " "))
    print("=" * 80)

def check_env_vars():
    """Check critical environment variables"""
    print_header("ENVIRONMENT VARIABLES")
    
    # Critical vars for login flow
    critical_vars = [
        "REQUIRE_EXPLICIT_DEVICE_AUTH",
        "SESSION_TYPE", 
        "REDIS_URL",
        "FLASK_ENV",
        "FLASK_DEBUG",
        "REDIS_HOST",
        "REDIS_PORT"
    ]
    
    for var in critical_vars:
        value = os.environ.get(var)
        if value is None:
            print(f"❌ {var}: Not set")
        else:
            print(f"✓ {var}: {value}")

def test_redis_connection():
    """Test Redis connection using different configurations"""
    print_header("REDIS CONNECTION TEST")
    
    # Method 1: Using REDIS_URL if available
    redis_url = os.environ.get('REDIS_URL')
    if redis_url:
        try:
            print(f"Testing connection using REDIS_URL: {redis_url}")
            r = redis.from_url(redis_url, decode_responses=True)
            result = r.ping()
            print(f"✓ Redis ping via REDIS_URL: {result}")
        except Exception as e:
            print(f"❌ Redis connection error via REDIS_URL: {e}")
    else:
        print("❌ REDIS_URL environment variable not set")
    
    # Method 2: Using REDIS_HOST and REDIS_PORT
    redis_host = os.environ.get('REDIS_HOST', 'redis')
    redis_port = int(os.environ.get('REDIS_PORT', 6379))
    try:
        print(f"Testing connection using host/port: {redis_host}:{redis_port}")
        r = redis.Redis(host=redis_host, port=redis_port, db=1, decode_responses=True)
        result = r.ping()
        print(f"✓ Redis ping via host/port: {result}")
        
        # Try setting and getting a value
        test_key = f"test_{int(time.time())}"
        r.set(test_key, "Test value")
        test_value = r.get(test_key)
        print(f"✓ Redis set/get test: {test_value}")
    except Exception as e:
        print(f"❌ Redis connection error via host/port: {e}")
    
    # Method 3: Using direct connection to container
    try:
        print(f"Testing direct connection to redis:6379")
        r = redis.Redis(host='redis', port=6379, db=1, decode_responses=True)
        result = r.ping()
        print(f"✓ Redis direct ping: {result}")
    except Exception as e:
        print(f"❌ Redis direct connection error: {e}")

def fix_environment():
    """Fix environment by creating or updating .env.override"""
    print_header("FIXING ENVIRONMENT")
    
    try:
        env_override_path = '/app/.env.override'
        
        print(f"Creating/updating {env_override_path}")
        with open(env_override_path, 'w') as f:
            f.write("""# Generated by direct_redis_test.py on {date}
# This file contains critical environment fixes for login issues

# Fix login loop issue
REQUIRE_EXPLICIT_DEVICE_AUTH=False

# Ensure sessions are using Redis
SESSION_TYPE=redis

# Explicitly set Redis URL to ensure connectivity
REDIS_URL=redis://redis:6379/1

# Ensure debug is enabled for troubleshooting
FLASK_DEBUG=True
""".format(date=datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
        
        print(f"✓ Successfully updated {env_override_path}")
        print("✓ To apply changes, restart the backend container:")
        print("   docker-compose restart backend")
        return True
    except Exception as e:
        print(f"❌ Error creating .env.override: {e}")
        return False

if __name__ == "__main__":
    print_header("DIRECT REDIS TEST")
    print(f"Running tests at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Check environment variables
    check_env_vars()
    
    # Test Redis connection
    test_redis_connection()
    
    # Fix environment if needed
    fix_environment()
    
    print_header("COMPLETED")
