"""Add trusted_mac_address to User model

Revision ID: 0d51dda0b4db
Revises: ad4cc568a10b
Create Date: 2025-07-02 12:14:53.594794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d51dda0b4db'
down_revision = 'ad4cc568a10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted_mac_address', sa.String(length=17), nullable=True, comment='MAC Address perangkat terpercaya untuk bypass & pemblokiran.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trusted_mac_address')

    # ### end Alembic commands ###
