"""initial_database_schema_final

Revision ID: 118c46525778
Revises: 
Create Date: 2025-05-07 17:44:33.760440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118c46525778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_quota_mb', sa.Integer(), nullable=False),
    sa.Column('speed_limit_kbps', sa.Integer(), nullable=True),
    sa.Column('mikrotik_profile_name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_packages_name')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index('ix_packages_mikrotik_profile_name', ['mikrotik_profile_name'], unique=False)
        batch_op.create_index('ix_packages_name', ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('blok', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='user_blok_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='user_role_enum'), server_default=sa.text("'USER'::user_role_enum"), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approval_status_enum'), server_default=sa.text("'PENDING_APPROVAL'::approval_status_enum"), nullable=False),
    sa.Column('mikrotik_password', sa.String(length=255), nullable=True),
    sa.Column('total_quota_purchased_mb', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_quota_used_mb', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('device_brand', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('raw_user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_users_phone_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_phone_number', ['phone_number'], unique=True)

    op.create_table('daily_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('usage_mb', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_daily_usage_logs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_daily_usage_logs_user_log_date')
    )
    with op.batch_alter_table('daily_usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_daily_usage_logs_log_date', ['log_date'], unique=False)
        batch_op.create_index('ix_daily_usage_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_daily_usage_logs_user_id_log_date', ['user_id', 'log_date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('midtrans_order_id', sa.String(length=100), nullable=False),
    sa.Column('midtrans_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('snap_token', sa.String(length=200), nullable=True),
    sa.Column('snap_redirect_url', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED', 'UNKNOWN', name='transaction_status_enum'), server_default=sa.text("'PENDING'::transaction_status_enum"), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('va_number', sa.String(length=50), nullable=True),
    sa.Column('payment_code', sa.String(length=50), nullable=True),
    sa.Column('biller_code', sa.String(length=20), nullable=True),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('hotspot_password', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name='fk_transactions_package_id_packages', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('midtrans_order_id', name='uq_transactions_midtrans_order_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_midtrans_order_id', ['midtrans_order_id'], unique=True)
        batch_op.create_index('ix_transactions_midtrans_transaction_id', ['midtrans_transaction_id'], unique=False)
        batch_op.create_index('ix_transactions_package_id', ['package_id'], unique=False)
        batch_op.create_index('ix_transactions_status', ['status'], unique=False)
        batch_op.create_index('ix_transactions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_id')
        batch_op.drop_index('ix_transactions_status')
        batch_op.drop_index('ix_transactions_package_id')
        batch_op.drop_index('ix_transactions_midtrans_transaction_id')
        batch_op.drop_index('ix_transactions_midtrans_order_id')

    op.drop_table('transactions')
    with op.batch_alter_table('daily_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_usage_logs_user_id_log_date')
        batch_op.drop_index('ix_daily_usage_logs_user_id')
        batch_op.drop_index('ix_daily_usage_logs_log_date')

    op.drop_table('daily_usage_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_phone_number')

    op.drop_table('users')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index('ix_packages_name')
        batch_op.drop_index('ix_packages_mikrotik_profile_name')

    op.drop_table('packages')
    # ### end Alembic commands ###
