"""add_blocking_reason_to_user_model

Revision ID: 15dbcd2c8f16
Revises: c15fa9f06db5
Create Date: 2025-07-26 15:07:41.158141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15dbcd2c8f16'
down_revision = 'c15fa9f06db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocking_reason', sa.String(length=255), nullable=True, comment='Alasan pemblokiran user oleh admin.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blocking_reason')

    # ### end Alembic commands ###
