# migrations/versions/419cec75e1d6_add_package_profiles_and_relate_to_.py
"""Add package profiles and relate to packages

Revision ID: 419cec75e1d6
Revises: a1e10e41e525
Create Date: 2025-06-06 19:45:25.420094

"""
from alembic import op
import sqlalchemy as sa
import uuid # Import uuid

# revision identifiers, used by Alembic.
revision = '419cec75e1d6'
down_revision = 'a1e10e41e525'
branch_labels = None
depends_on = None

def upgrade():
    # ### Tahap 1: Buat tabel package_profiles ###
    package_profiles_table = op.create_table('package_profiles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('profile_name', sa.String(length=100), nullable=False, comment='Nama profil di Mikrotik, cth: profile-quota-10gb'),
        sa.Column('data_quota_gb', sa.Numeric(precision=8, scale=2), nullable=True, comment='Kuota dalam GB. NULL jika is_unlimited=true'),
        sa.Column('is_unlimited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('profile_name', name='uq_package_profiles_name')
    )
    with op.batch_alter_table('package_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_package_profiles_name', ['profile_name'], unique=True)

    # --- PENANGANAN DATA YANG SUDAH ADA ---
    # ### Tahap 2: Buat satu profil default untuk dihubungkan ke paket yang sudah ada ###
    default_profile_id = str(uuid.uuid4())
    op.bulk_insert(package_profiles_table,
        [
            {
                'id': default_profile_id,
                'profile_name': 'default-migrated-profile',
                'data_quota_gb': 1, # Beri nilai default
                'is_unlimited': False,
                'description': 'Profil default yang dibuat otomatis saat migrasi data.'
            }
        ]
    )
    # ----------------------------------------

    # ### Tahap 3: Ubah tabel packages ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        # Tambahkan kolom profile_id, tapi buat nullable=True untuk sementara
        batch_op.add_column(sa.Column('profile_id', sa.UUID(), nullable=True))

    # ### Tahap 4: Update semua paket yang ada untuk menggunakan profil default ###
    op.execute(
        f"UPDATE packages SET profile_id = '{default_profile_id}'"
    )

    # ### Tahap 5: Setelah semua data terisi, ubah kolom menjadi NOT NULL dan buat foreign key ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        # Ubah kolom menjadi NOT NULL
        batch_op.alter_column('profile_id', existing_type=sa.UUID(), nullable=False)

        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nama paket yang dijual ke user, cth: Paket Juara 10GB',
               existing_nullable=False)
        
        # Buat index dan foreign key
        batch_op.create_index('ix_packages_profile_id', ['profile_id'], unique=False)
        batch_op.create_foreign_key('fk_packages_profile_id_package_profiles', 'package_profiles', ['profile_id'], ['id'], ondelete='RESTRICT')

        # Hapus kolom-kolom lama
        batch_op.drop_index(batch_op.f('ix_packages_mikrotik_profile_name'))
        batch_op.drop_column('speed_limit_kbps')
        batch_op.drop_column('mikrotik_profile_name')
        batch_op.drop_column('data_quota_gb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        # Tambahkan kembali kolom lama
        batch_op.add_column(sa.Column('data_quota_gb', sa.NUMERIC(precision=8, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mikrotik_profile_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False, server_default='default-migrated-profile'))
        batch_op.add_column(sa.Column('speed_limit_kbps', sa.INTEGER(), autoincrement=False, nullable=True))

        # Hapus foreign key dan kolom baru
        batch_op.drop_constraint('fk_packages_profile_id_package_profiles', type_='foreignkey')
        batch_op.drop_index('ix_packages_profile_id')
        batch_op.drop_column('profile_id')
        
        # Kembalikan index dan comment lama
        batch_op.create_index('ix_packages_mikrotik_profile_name', ['mikrotik_profile_name'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nama paket yang dijual ke user, cth: Paket Juara 10GB',
               existing_nullable=False)
    
    # Hapus tabel baru
    op.drop_table('package_profiles')
    # ### end Alembic commands ###