"""Add ondelete behavior to user foreign keys

Revision ID: 440535466127
Revises: 5b90c919b74c
Create Date: 2025-07-09 06:16:41.751043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '440535466127'
down_revision = '5b90c919b74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_approved_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_users_rejected_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_approved_by_id_users', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_users_rejected_by_id_users', 'users', ['rejected_by_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('rejected_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint('fk_users_rejected_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_users_approved_by_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_rejected_by_id_users'), 'users', ['rejected_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_users_approved_by_id_users'), 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###
