"""Set ondelete rule for promo event creator

Revision ID: 5b90c919b74c
Revises: 0d51dda0b4db
Create Date: 2025-07-09 06:02:09.391540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b90c919b74c'
down_revision = '0d51dda0b4db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('promo_events_created_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('blok',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='user_blok_enum', native_enum=False),
               existing_nullable=True)
        batch_op.alter_column('kamar',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Kamar_1', 'Kamar_2', 'Kamar_3', 'Kamar_4', 'Kamar_5', 'Kamar_6', name='user_kamar_enum', native_enum=False),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('kamar',
               existing_type=sa.Enum('Kamar_1', 'Kamar_2', 'Kamar_3', 'Kamar_4', 'Kamar_5', 'Kamar_6', name='user_kamar_enum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('blok',
               existing_type=sa.Enum('A', 'B', 'C', 'D', 'E', 'F', name='user_blok_enum', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('promo_events_created_by_id_fkey'), 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###
