"""alembic revision create_user_login_history_table

Revision ID: 6b610baac42d
Revises: a0443156617c
Create Date: 2025-06-04 17:34:20.105050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b610baac42d'
down_revision = 'a0443156617c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_string', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_history_user_id'))

    op.drop_table('user_login_history')
    # ### end Alembic commands ###
