"""add_user_audit_and_tracking_fields

Revision ID: 6babf097f528
Revises: 118c46525778
Create Date: 2025-05-07 18:45:28.486536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6babf097f528'
down_revision = '118c46525778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_users_rejected_by_id_users', 'users', ['rejected_by_id'], ['id'])
        batch_op.create_foreign_key('fk_users_approved_by_id_users', 'users', ['approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_approved_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_users_rejected_by_id_users', type_='foreignkey')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('rejected_by_id')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
