"""Implement UserKamar enum and role-based validation for blok/kamar

Revision ID: 76badf8cb3dc
Revises: 6babf097f528
Create Date: 2025-05-08 05:53:15.219949 # Sesuaikan tanggal jika perlu

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76badf8cb3dc'
down_revision = '6babf097f528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Buat tipe Enum 'user_kamar_enum' secara eksplisit SEBELUM kolom ditambahkan
    user_kamar_enum = postgresql.ENUM('1', '2', '3', '4', '5', '6', name='user_kamar_enum')
    user_kamar_enum.create(op.get_bind(), checkfirst=True) # checkfirst=True agar aman jika dijalankan ulang

    # 2. Gunakan batch_alter_table untuk operasi kolom
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Tambahkan kolom 'kamar' menggunakan tipe Enum yang SUDAH dibuat
        # Gunakan postgresql.ENUM lagi di sini tapi create_type=False (atau tidak perlu dispesifikasikan)
        # karena tipenya sudah dibuat oleh user_kamar_enum.create() di atas.
        # Cukup spesifikasikan nama tipenya.
        batch_op.add_column(sa.Column('kamar', sa.Enum(name='user_kamar_enum'), nullable=True))

        # Ubah kolom 'blok' agar bisa NULL
        batch_op.alter_column('blok',
                              existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', name='user_blok_enum'),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Kembalikan kolom 'blok' menjadi NOT NULL
        batch_op.alter_column('blok',
                              existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'F', name='user_blok_enum'),
                              nullable=False)
        # Hapus kolom 'kamar'
        batch_op.drop_column('kamar')

    # Hapus tipe Enum 'user_kamar_enum' dari database SETELAH kolom dihapus
    user_kamar_enum = postgresql.ENUM('1', '2', '3', '4', '5', '6', name='user_kamar_enum')
    user_kamar_enum.drop(op.get_bind(), checkfirst=True) # checkfirst=True agar aman jika dijalankan ulang

    # ### end Alembic commands ###