"""Add bonus_duration_days to promo_events

Revision ID: 779e989a2bd7
Revises: d5c24b52c59a
Create Date: 2025-06-11 21:08:05.769221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779e989a2bd7'
down_revision = 'd5c24b52c59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_duration_days', sa.Integer(), nullable=True, comment='Durasi masa aktif bonus dalam hari'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.drop_column('bonus_duration_days')

    # ### end Alembic commands ###
