"""Add status field to UserDevice model

Revision ID: 7e38a5142e3b
Revises: 20250811_01
Create Date: 2025-08-18 15:29:24.675094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e38a5142e3b'
down_revision = '20250811_01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='device_status_enum', native_enum=False), nullable=False))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=True, comment='User Agent yang digunakan saat perangkat didaftarkan'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='Alamat IP terakhir yang terasosiasi dengan perangkat (opsional)',
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_devices_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_status'))
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='Alamat IP terakhir yang terasosiasi dengan perangkat (opsional)',
               existing_nullable=True)
        batch_op.drop_column('user_agent')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
