"""Add last login ip and mac to user table

Revision ID: 804b8628b257
Revises: 440535466127
Create Date: 2025-07-11 16:13:39.893367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '804b8628b257'
down_revision = '440535466127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='Alamat IP terakhir yang digunakan user untuk login.'))
        batch_op.add_column(sa.Column('last_login_mac', sa.String(length=17), nullable=True, comment='Alamat MAC terakhir yang digunakan user untuk login (jika terdeteksi).'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_mac')
        batch_op.drop_column('last_login_ip')

    # ### end Alembic commands ###
