"""Baru

Revision ID: 8d8c1d749fa8
Revises: 
Create Date: 2025-06-10 20:11:09.676418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8c1d749fa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False, comment="Kunci unik untuk pengaturan, misal: 'APP_NAME'"),
    sa.Column('setting_value', sa.Text(), nullable=True, comment='Nilai dari pengaturan, bisa terenkripsi'),
    sa.Column('description', sa.Text(), nullable=True, comment='Penjelasan mengenai fungsi pengaturan ini'),
    sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('package_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('package_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_profiles_profile_name'), ['profile_name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('blok', sa.String(length=10), nullable=True),
    sa.Column('kamar', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPER_ADMIN', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('approval_status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approval_status_enum', native_enum=False), nullable=False),
    sa.Column('mikrotik_password', sa.String(length=255), nullable=True),
    sa.Column('total_quota_purchased_mb', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('total_quota_used_mb', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('quota_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_unlimited_user', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('device_brand', sa.String(length=100), nullable=True),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('raw_user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by_id', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name='fk_users_approved_by_id_users'),
    sa.ForeignKeyConstraint(['rejected_by_id'], ['users.id'], name='fk_users_rejected_by_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', name='uq_users_phone_number')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_phone_number', ['phone_number'], unique=True)

    op.create_table('daily_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('usage_mb', sa.Numeric(precision=15, scale=2), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_daily_usage_logs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'log_date', name='uq_daily_usage_logs_user_log_date')
    )
    with op.batch_alter_table('daily_usage_logs', schema=None) as batch_op:
        batch_op.create_index('ix_daily_usage_logs_log_date', ['log_date'], unique=False)
        batch_op.create_index('ix_daily_usage_logs_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_daily_usage_logs_user_id_log_date', ['user_id', 'log_date'], unique=False)

    op.create_table('notification_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('NEW_USER_REGISTRATION', 'ROLE_UPGRADE_TO_ADMIN', 'ROLE_DOWNGRADE_TO_USER', name='notification_type_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_user_id', 'notification_type', name='uq_notification_recipient_user_type')
    )
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.create_index('ix_notification_recipients_admin_user_id', ['admin_user_id'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_quota_gb', sa.Numeric(precision=8, scale=2), nullable=False, comment='Kuota dalam GB. 0 berarti unlimited.'),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['package_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_name'), ['name'], unique=True)

    op.create_table('user_login_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('login_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent_string', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_login_history_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('midtrans_order_id', sa.String(length=100), nullable=False),
    sa.Column('midtrans_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('snap_token', sa.String(length=200), nullable=True),
    sa.Column('snap_redirect_url', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'EXPIRED', 'CANCELLED', 'UNKNOWN', name='transaction_status_enum', native_enum=False), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('va_number', sa.String(length=50), nullable=True),
    sa.Column('payment_code', sa.String(length=50), nullable=True),
    sa.Column('biller_code', sa.String(length=20), nullable=True),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('hotspot_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name='fk_transactions_package_id_packages', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('midtrans_order_id', name='uq_transactions_midtrans_order_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_midtrans_order_id', ['midtrans_order_id'], unique=True)
        batch_op.create_index('ix_transactions_midtrans_transaction_id', ['midtrans_transaction_id'], unique=False)
        batch_op.create_index('ix_transactions_package_id', ['package_id'], unique=False)
        batch_op.create_index('ix_transactions_status', ['status'], unique=False)
        batch_op.create_index('ix_transactions_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_id')
        batch_op.drop_index('ix_transactions_status')
        batch_op.drop_index('ix_transactions_package_id')
        batch_op.drop_index('ix_transactions_midtrans_transaction_id')
        batch_op.drop_index('ix_transactions_midtrans_order_id')

    op.drop_table('transactions')
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_login_history_user_id'))

    op.drop_table('user_login_history')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_name'))

    op.drop_table('packages')
    with op.batch_alter_table('notification_recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_recipients_admin_user_id')

    op.drop_table('notification_recipients')
    with op.batch_alter_table('daily_usage_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_usage_logs_user_id_log_date')
        batch_op.drop_index('ix_daily_usage_logs_user_id')
        batch_op.drop_index('ix_daily_usage_logs_log_date')

    op.drop_table('daily_usage_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_phone_number')

    op.drop_table('users')
    with op.batch_alter_table('package_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_profiles_profile_name'))

    op.drop_table('package_profiles')
    op.drop_table('application_settings')
    # ### end Alembic commands ###
