"""Update package model with duration and quota in GB

Revision ID: a1e10e41e525
Revises: 6b610baac42d
Create Date: 2025-06-06 19:04:42.792611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e10e41e525'
down_revision = '6b610baac42d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('data_quota_gb', sa.Numeric(precision=8, scale=2), server_default='0.00', nullable=False))
        batch_op.drop_column('data_quota_mb')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_quota_mb', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_quota_gb')
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
