"""Add is_blocked status to User model for status-based management

Revision ID: ad4cc568a10b
Revises: c81cfcd63139
Create Date: 2025-06-27 14:15:22.605307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4cc568a10b'
down_revision = 'c81cfcd63139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Flag untuk menandai user diblokir oleh admin.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
