"""refactor package profiles to include duration

Revision ID: b96144e51cae
Revises: 419cec75e1d6
Create Date: 2025-06-06 20:22:55.304591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96144e51cae'
down_revision = '419cec75e1d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), server_default='30', nullable=False))
        batch_op.alter_column('profile_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nama profil di Mikrotik',
               existing_comment='Nama profil di Mikrotik, cth: profile-quota-10gb',
               existing_nullable=False)
        batch_op.alter_column('data_quota_gb',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False,
               comment='Kuota dalam GB. 0 berarti unlimited.',
               existing_comment='Kuota dalam GB. NULL jika is_unlimited=true')
        batch_op.drop_column('is_unlimited')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nama paket yang dijual ke user',
               existing_comment='Nama paket yang dijual ke user, cth: Paket Juara 10GB',
               existing_nullable=False)
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nama paket yang dijual ke user, cth: Paket Juara 10GB',
               existing_comment='Nama paket yang dijual ke user',
               existing_nullable=False)

    with op.batch_alter_table('package_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_unlimited', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.alter_column('data_quota_gb',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True,
               comment='Kuota dalam GB. NULL jika is_unlimited=true',
               existing_comment='Kuota dalam GB. 0 berarti unlimited.')
        batch_op.alter_column('profile_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nama profil di Mikrotik, cth: profile-quota-10gb',
               existing_comment='Nama profil di Mikrotik',
               existing_nullable=False)
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
