"""Implement multi-device management

Revision ID: c15fa9f06db5
Revises: c1190b784073
Create Date: 2025-07-17 09:18:47.740424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15fa9f06db5'
down_revision = 'c1190b784073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index('ix_user_devices_mac_address', ['mac_address'], unique=True)
        batch_op.create_index('ix_user_devices_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trusted_mac_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted_mac_address', sa.VARCHAR(length=17), autoincrement=False, nullable=True, comment='MAC Address perangkat terpercaya untuk bypass & pemblokiran.'))

    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_user_devices_user_id')
        batch_op.drop_index('ix_user_devices_mac_address')

    op.drop_table('user_devices')
    # ### end Alembic commands ###
