"""Expand length of AdminActionType enum

Revision ID: c465d250f8b2
Revises: 
Create Date: 2025-06-21 06:41:39.513141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c465d250f8b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=23),
               type_=sa.Enum('CREATE_USER', 'APPROVE_USER', 'REJECT_USER', 'CHANGE_USER_ROLE', 'UPGRADE_TO_ADMIN', 'DOWNGRADE_TO_USER', 'DOWNGRADE_FROM_ADMIN', 'INJECT_QUOTA', 'SET_UNLIMITED_STATUS', 'REVOKE_UNLIMITED_STATUS', 'ACTIVATE_USER', 'DEACTIVATE_USER', 'RESET_HOTSPOT_PASSWORD', 'GENERATE_ADMIN_PASSWORD', 'MANUAL_USER_DELETE', 'UPDATE_USER_PROFILE', 'PROCESS_QUOTA_REQUEST_APPROVE', 'PROCESS_QUOTA_REQUEST_REJECT', 'PROCESS_QUOTA_REQUEST_PARTIALLY_APPROVED', name='admin_action_type_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_logs', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.Enum('CREATE_USER', 'APPROVE_USER', 'REJECT_USER', 'CHANGE_USER_ROLE', 'UPGRADE_TO_ADMIN', 'DOWNGRADE_TO_USER', 'DOWNGRADE_FROM_ADMIN', 'INJECT_QUOTA', 'SET_UNLIMITED_STATUS', 'REVOKE_UNLIMITED_STATUS', 'ACTIVATE_USER', 'DEACTIVATE_USER', 'RESET_HOTSPOT_PASSWORD', 'GENERATE_ADMIN_PASSWORD', 'MANUAL_USER_DELETE', 'UPDATE_USER_PROFILE', 'PROCESS_QUOTA_REQUEST_APPROVE', 'PROCESS_QUOTA_REQUEST_REJECT', 'PROCESS_QUOTA_REQUEST_PARTIALLY_APPROVED', name='admin_action_type_enum', native_enum=False),
               type_=sa.VARCHAR(length=23),
               existing_nullable=False)

    # ### end Alembic commands ###
