"""Add granted_details to QuotaRequest model

Revision ID: c56ce35abcc8
Revises: c465d250f8b2
Create Date: 2025-06-21 07:16:47.928373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56ce35abcc8'
down_revision = 'c465d250f8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quota_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted_details', sa.Text(), nullable=True, comment="Detail persetujuan parsial dlm JSON, misal: {'granted_mb': 5120, 'granted_duration_days': 15}"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quota_requests', schema=None) as batch_op:
        batch_op.drop_column('granted_details')

    # ### end Alembic commands ###
