"""Add trusted_mac_address to User

Revision ID: d38b5d05c996
Revises: c15fa9f06db5
Create Date: 2025-07-20 08:26:54.587468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38b5d05c996'
down_revision = 'c15fa9f06db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted_mac_address', sa.String(length=17), nullable=True, comment='MAC Address perangkat utama yang terpercaya untuk bypass.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('trusted_mac_address')

    # ### end Alembic commands ###
