"""Add previous_blok_kamar to users

Revision ID: d3f3321f015d
Revises: 8d8c1d749fa8
Create Date: 2025-06-10 22:06:48.905935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3f3321f015d'
down_revision = '8d8c1d749fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_blok', sa.String(length=10), nullable=True, comment='Menyimpan data blok terakhir sebelum diupgrade ke admin'))
        batch_op.add_column(sa.Column('previous_kamar', sa.String(length=20), nullable=True, comment='Menyimpan data kamar terakhir sebelum diupgrade ke admin'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('previous_kamar')
        batch_op.drop_column('previous_blok')

    # ### end Alembic commands ###
