"""Add Event Dan Promo

Revision ID: d5c24b52c59a
Revises: d3f3321f015d
Create Date: 2025-06-11 17:15:04.520740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c24b52c59a'
down_revision = 'd3f3321f015d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('BONUS_REGISTRATION', 'GENERAL_ANNOUNCEMENT', name='promo_event_type_enum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SCHEDULED', 'EXPIRED', 'ARCHIVED', name='promo_event_status_enum', native_enum=False), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bonus_value_mb', sa.BigInteger(), nullable=True, comment='Nilai bonus dalam MB untuk event tipe BONUS_REGISTRATION'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_promo_events_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_events_status'))
        batch_op.drop_index(batch_op.f('ix_promo_events_name'))

    op.drop_table('promo_events')
    # ### end Alembic commands ###
