"""Add mac address to user login history

Revision ID: e3ff9ae58285
Revises: 804b8628b257
Create Date: 2025-07-11 16:36:49.907909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ff9ae58285'
down_revision = '804b8628b257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mac_address', sa.String(length=17), nullable=True, comment='MAC Address yang digunakan saat login.'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_login_history', schema=None) as batch_op:
        batch_op.drop_column('mac_address')

    # ### end Alembic commands ###
