"""add fup and habis notif timestamps

Revision ID: eeb1e7f91a6c
Revises: e3ff9ae58285
Create Date: 2025-07-14 03:47:39.149738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb1e7f91a6c'
down_revision = 'e3ff9ae58285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_fup_notif_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu terakhir notifikasi status FUP aktif dikirim'))
        batch_op.add_column(sa.Column('last_habis_notif_at', sa.DateTime(timezone=True), nullable=True, comment='Waktu terakhir notifikasi status KUOTA HABIS dikirim'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_habis_notif_at')
        batch_op.drop_column('last_fup_notif_at')

    # ### end Alembic commands ###
