# .github/workflows/deploy-to-dockerhub.yml
name: Build and Push Docker Images (ARM64)

on:
  push:
    branches:
      - main # Jalankan workflow ini saat ada push ke branch 'main'
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual dari GitHub UI

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu di GitHub Actions

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 # Mengambil kode dari repository GitHub

    - name: Set up QEMU
      # QEMU diperlukan untuk emulasi arsitektur. Tanpa ini, runner (AMD64)
      # tidak akan bisa membangun image untuk arsitektur ARM64.
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      # Buildx adalah fitur Docker yang memungkinkan build image multi-platform.
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      # Menggunakan secrets yang sudah Anda set di repository GitHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Image (ARM64)
      uses: docker/build-push-action@v5
      with:
        context: ./backend # Lokasi Dockerfile backend relatif terhadap root repo
        file: ./backend/Dockerfile
        platforms: linux/arm64 # **TARGET UTAMA: Membangun image untuk arsitektur ARM64**
        push: true # Mengunggah image ke Docker Hub
        tags: babahdigital/hotspot_backend:latest # Tag image di Docker Hub

    - name: Build and Push Frontend Image (ARM64)
      uses: docker/build-push-action@v5
      with:
        context: ./frontend # Lokasi Dockerfile frontend
        file: ./frontend/Dockerfile
        platforms: linux/arm64 # **TARGET UTAMA: Membangun image untuk arsitektur ARM64**
        push: true # Mengunggah image ke Docker Hub
        tags: babahdigital/hotspot_frontend:latest # Tag image di Docker Hub

    - name: Verify Images on Docker Hub
      run: |
        echo "Proses build dan push ke Docker Hub untuk arsitektur ARM64 selesai."
        echo "Image yang diunggah:"
        echo "  - babahdigital/hotspot_backend:latest"
        echo "  - babahdigital/hotspot_frontend:latest"